name: homelab
services:
  paas:
    build:
      context: ./
      dockerfile: ./services/paas/Dockerfile
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./paas-config/:/etc/homelab-paas
    environment:
      PAAS_ROOT_DOMAIN: ${PAAS_ROOT_DOMAIN}
      PAAS_CONTAINER_NAME: /homelab-paas-1

      PAAS_AUTH_CLIENT_ID: ${PAAS_AUTH_CLIENT_ID}
      PAAS_AUTH_CLIENT_SECRET: ${PAAS_AUTH_CLIENT_SECRET}
      PAAS_AUTH_JWT_SECRET: ${PAAS_AUTH_JWT_SECRET}
      PAAS_AUTH_AUTHORIZED_USERS: ${PAAS_AUTH_AUTHORIZED_USERS}
      PAAS_AUTH_PAAS_ADMIN_USERS: ${PAAS_AUTH_PAAS_ADMIN_USERS}

      PAAS_TLS_NOTIFICATION_EMAIL: ${PAAS_TLS_NOTIFICATION_EMAIL}
      PAAS_TLS_LETSENCRYPT_ENV: ${PAAS_TLS_LETSENCRYPT_ENV}
      PAAS_TLS_DIGITALOCEAN_DOMAIN: ${PAAS_TLS_DIGITALOCEAN_DOMAIN}
      PAAS_TLS_DIGITALOCEAN_ACCESS_TOKEN: ${PAAS_TLS_DIGITALOCEAN_ACCESS_TOKEN}
