name: Deploy
description: Deploy paas service
author: Maxine <9019624+maxine4j@users.noreply.github.com>
inputs:
  deploy-token:
    description: 'The deployment token used to authenticate the deployment.'
    required: true
  service-descriptor-path:
    description: 'Path to the service descriptor YAML file.'
    required: true
  paas-base-url:
    description: 'Base URL for your paas, e.g. https://paas.example.com'
    required: true
outputs:
  success:
    description: 'Whether the deployment was successful.'
runs:
  using: composite
  steps:
    - name: Set up node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: Run action
      run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
